var Quo=function(){function a(d,b){d=d||f;d.__proto__=a.prototype;d.selector=b||"";return d}function c(d){if(d){var b=c.getDomainSelector(d);return a(b,d)}else return a()}var f=[];c.extend=function(d){Array.prototype.slice.call(arguments,1).forEach(function(b){for(key in b)d[key]=b[key]});return d};a.prototype=c.fn={};return c}();window.Quo=Quo;"$$"in window||(window.$$=Quo);
(function(a){function c(b){return b.filter(function(g){return g!==undefined&&g!==null})}var f=Object.prototype,d=[];a.toType=function(b){return f.toString.call(b).match(/\s([a-z|A-Z]+)/)[1].toLowerCase()};a.isOwnProperty=function(b,g){return f.hasOwnProperty.call(b,g)};a.getDomainSelector=function(b){var g=null,e=[1,9,11],l=a.toType(b);if(l==="array")g=c(b);else if(l==="string")g=a.query(document,b);else if(e.indexOf(b.nodeType)>=0||b===window)g=[b];return g};a.map=function(b,g){var e=[],l;if(a.toType(b)===
"array")for(l=0;l<b.length;l++){var i=g(b[l],l);i!=null&&e.push(i)}else for(l in b){i=g(b[l],l);i!=null&&e.push(i)}return e.length>0?[].concat.apply([],e):e};a.each=function(b,g){var e;if(a.toType(b)==="array")for(e=0;e<b.length;e++){if(g.call(b[e],e,b[e])===false)break}else for(e in b)if(g.call(b[e],e,b[e])===false)break;return b};a.mix=function(){for(var b={},g=0,e=arguments.length;g<e;g++){var l=arguments[g],i;for(i in l)if(a.isOwnProperty(l,i)&&l[i]!==undefined)b[i]=l[i]}return b};a.fn.forEach=
d.forEach;a.fn.indexOf=d.indexOf;a.fn.map=function(b){return a.map(this,function(g,e){return b.call(g,e,g)})};a.fn.instance=function(b){return this.map(function(){return this[b]})};a.fn.filter=function(b){return a([].filter.call(this,function(g){return g.parentNode&&a.query(g.parentNode,b).indexOf(g)>=0}))}})(Quo);
(function(a){a.fn.attr=function(c,f){return a.toType(c)==="string"&&f===undefined?this[0].getAttribute(c):this.each(function(){this.setAttribute(c,f)})};a.fn.data=function(c,f){return this.attr("data-"+c,f)};a.fn.val=function(c){return a.toType(c)==="string"?this.each(function(){this.value=c}):this.length>0?this[0].value:null};a.fn.show=function(){return this.style("display","block")};a.fn.hide=function(){return this.style("display","none")};a.fn.height=function(){return this.offset().height};a.fn.width=
function(){return this.offset().width};a.fn.offset=function(){var c=this[0].getBoundingClientRect();return{left:c.left+window.pageXOffset,top:c.top+window.pageYOffset,width:c.width,height:c.height}};a.fn.remove=function(){return this.each(function(){this.parentNode!=null&&this.parentNode.removeChild(this)})}})(Quo);
(function(a){var c=/WebKit\/([\d.]+)/,f={android:/(Android)\s+([\d.]+)/,ipad:/(iPad).*OS\s([\d_]+)/,iphone:/(iPhone\sOS)\s([\d_]+)/,blackberry:/(BlackBerry).*Version\/([\d.]+)/,webos:/(webOS|hpwOS)[\s\/]([\d.]+)/},d=null;a.isMobile=function(){d=d||b();return d.isMobile};a.environment=function(){return d=d||b()};a.isOnline=function(){return navigator.onLine};var b=function(){var g=navigator.userAgent,e={},l=g.match(c);e.browser=l?l[0]:g;var i;for(os in f)if(l=g.match(f[os])){i={name:os==="iphone"||
os==="ipad"?"ios":os,version:l[2].replace("_",".")};break}e.os=i;e.isMobile=e.os?true:false;return e}})(Quo);
(function(a){a.fn.text=function(c){return!c?this[0].textContent:this.each(function(){this.textContent=c})};a.fn.html=function(c){return a.toType("value")==="string"?this.each(function(){this.innerHTML=c}):this[0].innerHTML};a.fn.append=function(c){return this.each(function(){if(a.toType(c)==="string"){var f=document.createElement();f.innerHTML=c;this.appendChild(f.firstChild)}else this.parentNode.insertBefore(c)})};a.fn.prepend=function(c){return this.each(function(){if(a.toType(c)==="string")this.innerHTML=
c+this.innerHTML;else{var f=this.parentNode;f.insertBefore(c,f.firstChild)}})};a.fn.empty=function(){return this.each(function(){this.innerHTML=null})}})(Quo);
(function(a){a.query=function(d,b){var g=document.querySelectorAll(b);return g=Array.prototype.slice.call(g)};a.fn.parent=function(d){var b=d?c(this):this.instance("parentNode");return f(b,d)};a.fn.siblings=function(d){var b=this.map(function(g,e){return Array.prototype.slice.call(e.parentNode.children).filter(function(l){return l!==e})});return f(b,d)};a.fn.children=function(d){var b=this.map(function(){return Array.prototype.slice.call(this.children)});return f(b,d)};a.fn.get=function(d){return d===
undefined?this:this[d]};a.fn.first=function(){return a(this[0])};a.fn.last=function(){return a(this[this.length-1])};a.fn.closest=function(d,b){var g=this[0],e=a(d);for(e.length||(g=null);g&&e.indexOf(g)<0;)g=g!==b&&g!==document&&g.parentNode;return a(g)};a.fn.each=function(d){this.forEach(function(b,g){d.call(b,g,b)});return this};var c=function(d){for(var b=[];d.length>0;)d=a.map(d,function(g){if((g=g.parentNode)&&g!==document&&b.indexOf(g)<0){b.push(g);return g}});return b},f=function(d,b){return b===
undefined?a(d):a(d).filter(b)}})(Quo);
(function(a){function c(f,d){return d.split(/\s+/g).indexOf(f)>=0}a.fn.addClass=function(f){return this.each(function(){c(f,this.className)||(this.className+=" "+f)})};a.fn.removeClass=function(f){return this.each(function(){if(c(f,this.className))this.className=this.className.replace(f," ")})};a.fn.toggleClass=function(f){return this.each(function(){if(c(f,this.className))this.className=this.className.replace(f," ");else this.className+=" "+f})};a.fn.hasClass=function(f){return c(f,this[0].className)};
a.fn.style=function(f,d){return!d?this[0].style[f]||document.defaultView.getComputedStyle(this[0],"")[f]:this.each(function(){this.style[f]=d})}})(Quo);
(function(a){function c(i,h){if(h.contentType)h.headers["Content-Type"]=h.contentType;if(h.dataType)h.headers.Accept=g[h.dataType];for(header in h.headers)i.setRequestHeader(header,h.headers[header])}function f(i,h){i.onreadystatechange={};i.abort();h.error.call(h.context,"QuoJS \u00bb $$.ajax : timeout exceeded",i,h)}function d(i,h){var k=i.responseText;if(k)if(h.dataType===b.MIME)try{k=JSON.parse(k)}catch(m){k=m;h.error.call(h.context,"Parse Error",i,h)}return k}var b={TYPE:"GET",MIME:"json"},g=
{script:"text/javascript, application/javascript",json:"application/json",xml:"application/xml, text/xml",html:"text/html",text:"text/plain"},e=0;a.ajaxSettings={type:b.TYPE,async:true,success:{},error:{},context:null,dataType:b.MIME,headers:{},xhr:function(){return new window.XMLHttpRequest},crossDomain:false,timeout:0};a.ajax=function(i){var h=a.mix(a.ajaxSettings,i);if(/=\?/.test(h.url))return a.jsonp(h);var k=h.xhr();k.onreadystatechange=function(){if(k.readyState===4){clearTimeout(m);if(k.status===
200){if(h.async){var q=d(k,h);h.success.call(h.context,q,k)}}else h.error.call(h.context,"QuoJS \u00bb $$.ajax",k,h)}};k.open(h.type,h.url,h.async);c(k,h);if(h.timeout>0)var m=setTimeout(function(){f(k,h)},h.timeout);k.send(h.data);return h.async?k:d(k,h)};a.jsonp=function(i){var h="jsonp"+ ++e,k=document.createElement("script"),m={abort:function(){a(k).remove();if(h in window)window[h]={}}},q;window[h]=function(s){clearTimeout(q);a(k).remove();delete window[h];i.success.call(i.context,s,m)};k.src=
i.url.replace(/=\?/,"="+h);a("head").append(k);if(i.timeout>0)q=setTimeout(function(){f(m,i)},i.timeout);return m};a.get=function(i,h,k,m){i+=l(h);return a.ajax({url:i,success:k,dataType:m})};a.post=function(i,h,k,m){return a.ajax({type:"POST",url:i,data:h,success:k,dataType:m,contentType:"application/x-www-form-urlencoded"})};a.json=function(i,h,k){i+=l(h);return a.ajax({url:i,success:k,dataType:b.MIME})};var l=function(i){var h="?",k;for(k in i)if(i.hasOwnProperty(k)){if(h!=="?")h+="&";h+=k+"="+
i[k]}return h==="?"?"":h}})(Quo);
(function(a){var c={touch:"touchstart",tap:"tap"},f=/complete|loaded|interactive/;["touch","tap"].forEach(function(d){a.fn[d]=function(b){a(document.body).delegate(this.selector,c[d],b);return this}});a.fn.on=function(d,b,g){return b===undefined||a.toType(b)==="function"?this.bind(d,b):this.delegate(b,d,g)};a.fn.off=function(d,b,g){return b===undefined||a.toType(b)==="function"?this.unbind(d,b):this.undelegate(b,d,g)};a.fn.ready=function(d){f.test(document.readyState)?d(a):document.addEventListener("DOMContentLoaded",
function(){d(a)},false);return this}})(Quo);
(function(a){function c(k,m,q,s,u){m=a.isMobile()?m:h[m];var w=k._id||(k._id=e++);w=l[w]||(l[w]=[]);u=u&&u(q,m);m={event:m,callback:q,selector:s,proxy:d(u,q,k),delegate:u,index:w.length};w.push(m);k.addEventListener(m.event,m.proxy,false)}function f(k,m,q,s){m=a.isMobile()?m:h[m];var u=k._id||(k._id=e++);b(u,m,q,s).forEach(function(w){delete l[u][w.index];k.removeEventListener(w.event,w.proxy,false)})}function d(k,m,q){m=k||m;return function(s){var u=m.apply(q,[s].concat(s.data));u===false&&s.preventDefault();
return u}}function b(k,m,q,s){return(l[k]||[]).filter(function(u){return u&&(!m||u.event==m)&&(!q||u.fn==q)&&(!s||u.selector==s)})}function g(k){var m=a.extend({originalEvent:k},k);a.each(i,function(q,s){m[q]=function(){this[s]=function(){return true};return k[q].apply(k,arguments)};m[s]=function(){return false}});return m}var e=1,l={},i={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"},h={touchstart:"mousedown",touchmove:"mousemove",
touchend:"mouseup",tap:"click",doubletap:"dblclick",orientationchange:"resize"};a.Event=function(k){var m=document.createEvent("Events");m.initEvent(k,true,true,null,null,null,null,null,null,null,null,null,null,null,null);return m};a.fn.bind=function(k,m){return this.each(function(){c(this,k,m)})};a.fn.unbind=function(k,m){return this.each(function(){f(this,k,m)})};a.fn.delegate=function(k,m,q){return this.each(function(s,u){c(u,m,q,k,function(w){return function(z){var y=a(z.target).closest(k,u).get(0);
if(y){var j=a.extend(g(z),{currentTarget:y,liveFired:u});return w.apply(y,[j].concat([].slice.call(arguments,1)))}}})})};a.fn.undelegate=function(k,m,q){return this.each(function(){f(this,m,q,k)})};a.fn.trigger=function(k){a.isMobile()||console.log("Event "+k+" captured.");if(a.toType(k)==="string")k=a.Event(k);return this.each(function(){this.dispatchEvent(k)})}})(Quo);
(function(a){function c(h){var k=Date.now(),m=k-(e.last||k);h=a.isMobile()?h.touches[0]:h;l&&clearTimeout(l);e={el:a("tagName"in h.target?h.target:h.target.parentNode),x1:h.pageX,y1:h.pageY,isDoubleTap:m>0&&m<=250?true:false,last:k};setTimeout(g,i)}function f(h){h=a.isMobile()?h.touches[0]:h;e.x2=h.pageX;e.y2=h.pageY}function d(){if(e.isDoubleTap){e.el.trigger("doubleTap");e={}}else if(e.x2>0||e.y2>0){(Math.abs(e.x1-e.x2)>30||Math.abs(e.y1-e.y2)>30)&&e.el.trigger("swipe")&&e.el.trigger("swipe"+(Math.abs(e.x1-
e.x2)>=Math.abs(e.y1-e.y2)?e.x1-e.x2>0?"Left":"Right":e.y1-e.y2>0?"Up":"Down"));e.x1=e.x2=e.y1=e.y2=e.last=0;e={}}else{e.el.trigger("tap");l=setTimeout(function(){l=null;e={}},250)}}function b(){e={};clearTimeout(l)}function g(){if(e.last&&Date.now()-e.last>=i){e.el.trigger("longTap");e={}}}var e={},l,i=750;["swipe","swipeLeft","swipeRight","swipeUp","swipeDown","doubleTap","longTap"].forEach(function(h){a.fn[h]=function(k){return this.on(h,k)}});a(document).ready(function(){var h=a(document.body);
h.bind("touchstart",c);h.bind("touchmove",f);h.bind("touchend",d);h.bind("touchcancel",b)})})(Quo);(function(){var a=Math,c=/webkit/i.test(navigator.appVersion)?"webkit":/firefox/i.test(navigator.userAgent)?"Moz":"opera"in window?"O":"";/android/gi.test(navigator.appVersion);var f=/iphone|ipad/gi.test(navigator.appVersion),d=/playbook/gi.test(navigator.appVersion),b=/hp-tablet/gi.test(navigator.appVersion),g="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix,e="ontouchstart"in window&&!b,l=c+"Transform"in document.documentElement.style,i=f||d,h=function(){return window.requestAnimationFrame||
window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(j){return setTimeout(j,17)}}(),k=window.cancelRequestAnimationFrame||window.webkitCancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||clearTimeout,m="onorientationchange"in window?"orientationchange":"resize",q=e?"touchstart":"mousedown",
s=e?"touchmove":"mousemove",u=e?"touchend":"mouseup",w=e?"touchcancel":"mouseup",z="translate"+(g?"3d(":"("),y=g?",0)":")";f=function(j,o){var n=document,r;this.wrapper=typeof j=="object"?j:n.getElementById(j);this.wrapper.style.overflow="hidden";this.scroller=this.wrapper.children[0];this.options={hScroll:true,vScroll:true,x:0,y:0,bounce:true,bounceLock:false,momentum:true,lockDirection:true,useTransform:true,useTransition:false,onRefresh:null,onBeforeScrollStart:function(p){for(var t=p.target;t.nodeType!=
1;)t=t.parentNode;t.tagName!="SELECT"&&t.tagName!="INPUT"&&t.tagName!="TEXTAREA"&&p.preventDefault()},onScrollStart:null,onBeforeScrollMove:null,onScrollMove:null,onBeforeScrollEnd:null,onScrollEnd:null,onTouchEnd:null,onDestroy:null};for(r in o)this.options[r]=o[r];this.x=this.options.x;this.y=this.options.y;this.options.useTransform=l?this.options.useTransform:false;this.options.hScrollbar=this.options.hScroll&&this.options.hScrollbar;this.options.vScrollbar=this.options.vScroll&&this.options.vScrollbar;
this.options.useTransition=i&&this.options.useTransition;this.scroller.style[c+"TransitionProperty"]=this.options.useTransform?"-"+c.toLowerCase()+"-transform":"top left";this.scroller.style[c+"TransitionDuration"]="0";this.scroller.style[c+"TransformOrigin"]="0 0";if(this.options.useTransition)this.scroller.style[c+"TransitionTimingFunction"]="cubic-bezier(0.33,0.66,0.66,1)";if(this.options.useTransform)this.scroller.style[c+"Transform"]=z+this.x+"px,"+this.y+"px"+y;else this.scroller.style.cssText+=
";position:absolute;top:"+this.y+"px;left:"+this.x+"px";this.refresh();this._bind(m,window);this._bind(q);e||this._bind("mouseout",this.wrapper)};f.prototype={enabled:true,x:0,y:0,steps:[],scale:1,handleEvent:function(j){switch(j.type){case q:if(!e&&j.button!==0)break;this._start(j);break;case s:this._move(j);break;case u:case w:this._end(j);break;case m:this._resize();break;case "mouseout":this._mouseout(j);break;case "webkitTransitionEnd":this._transitionEnd(j)}},_resize:function(){this.refresh()},
_pos:function(j,o){j=this.hScroll?j:0;o=this.vScroll?o:0;if(this.options.useTransform)this.scroller.style[c+"Transform"]=z+j+"px,"+o+"px"+y+" scale("+this.scale+")";else{j>>=0;o>>=0;this.scroller.style.left=j+"px";this.scroller.style.top=o+"px"}this.x=j;this.y=o},_start:function(j){var o=e?j.touches[0]:j,n,r;if(this.enabled){this.options.onBeforeScrollStart&&this.options.onBeforeScrollStart.call(this,j);this.options.useTransition&&this._transitionTime(0);this.zoomed=this.animating=this.moved=false;
this.dirY=this.dirX=this.absDistY=this.absDistX=this.distY=this.distX=0;if(this.options.momentum){if(this.options.useTransform){n=getComputedStyle(this.scroller,null)[c+"Transform"].replace(/[^0-9-.,]/g,"").split(",");r=n[4]*1;n=n[5]*1}else{r=getComputedStyle(this.scroller,null).left.replace(/[^0-9-]/g,"")*1;n=getComputedStyle(this.scroller,null).top.replace(/[^0-9-]/g,"")*1}if(r!=this.x||n!=this.y){this.options.useTransition?this._unbind("webkitTransitionEnd"):k(this.aniTime);this.steps=[];this._pos(r,
n)}}this.startX=this.x;this.startY=this.y;this.pointX=o.pageX;this.pointY=o.pageY;this.startTime=j.timeStamp||Date.now();this.options.onScrollStart&&this.options.onScrollStart.call(this,j);this._bind(s);this._bind(u);this._bind(w)}},_move:function(j){var o=e?j.touches[0]:j,n=o.pageX-this.pointX,r=o.pageY-this.pointY,p=this.x+n,t=this.y+r,v=j.timeStamp||Date.now();this.options.onBeforeScrollMove&&this.options.onBeforeScrollMove.call(this,j);this.pointX=o.pageX;this.pointY=o.pageY;if(p>0||p<this.maxScrollX)p=
this.options.bounce?this.x+n/2:p>=0||this.maxScrollX>=0?0:this.maxScrollX;if(t>0||t<this.maxScrollY)t=this.options.bounce?this.y+r/2:t>=0||this.maxScrollY>=0?0:this.maxScrollY;if(this.absDistX<6&&this.absDistY<6){this.distX+=n;this.distY+=r;this.absDistX=a.abs(this.distX);this.absDistY=a.abs(this.distY)}else{if(this.options.lockDirection)if(this.absDistX>this.absDistY+5){t=this.y;r=0}else if(this.absDistY>this.absDistX+5){p=this.x;n=0}this.moved=true;this._pos(p,t);this.dirX=n>0?-1:n<0?1:0;this.dirY=
r>0?-1:r<0?1:0;if(v-this.startTime>300){this.startTime=v;this.startX=this.x;this.startY=this.y}this.options.onScrollMove&&this.options.onScrollMove.call(this,j)}},_end:function(j){if(!(e&&j.touches.length!=0)){var o=e?j.changedTouches[0]:j,n,r,p={dist:0,time:0},t={dist:0,time:0},v=(j.timeStamp||Date.now())-this.startTime;n=this.x;r=this.y;this._unbind(s);this._unbind(u);this._unbind(w);this.options.onBeforeScrollEnd&&this.options.onBeforeScrollEnd.call(this,j);if(this.moved){if(v<300&&this.options.momentum){p=
n?this._momentum(n-this.startX,v,-this.x,this.scrollerW-this.wrapperW+this.x,this.options.bounce?this.wrapperW:0):p;t=r?this._momentum(r-this.startY,v,-this.y,this.maxScrollY<0?this.scrollerH-this.wrapperH+this.y:0,this.options.bounce?this.wrapperH:0):t;n=this.x+p.dist;r=this.y+t.dist;if(this.x>0&&n>0||this.x<this.maxScrollX&&n<this.maxScrollX)p={dist:0,time:0};if(this.y>0&&r>0||this.y<this.maxScrollY&&r<this.maxScrollY)t={dist:0,time:0}}if(p.dist||t.dist){o=a.max(a.max(p.time,t.time),10);this.scrollTo(n>>
0,r>>0,o)}else this._resetPos(200)}else{if(e){for(n=o.target;n.nodeType!=1;)n=n.parentNode;if(n.tagName!="SELECT"&&n.tagName!="INPUT"&&n.tagName!="TEXTAREA"){r=document.createEvent("MouseEvents");r.initMouseEvent("click",true,true,j.view,1,o.screenX,o.screenY,o.clientX,o.clientY,j.ctrlKey,j.altKey,j.shiftKey,j.metaKey,0,null);r._fake=true;n.dispatchEvent(r)}}this._resetPos(200)}this.options.onTouchEnd&&this.options.onTouchEnd.call(this,j)}},_resetPos:function(j){var o=this.x>=0?0:this.x<this.maxScrollX?
this.maxScrollX:this.x,n=this.y>=0||this.maxScrollY>0?0:this.y<this.maxScrollY?this.maxScrollY:this.y;if(o==this.x&&n==this.y){if(this.moved){this.options.onScrollEnd&&this.options.onScrollEnd.call(this);this.moved=false}}else this.scrollTo(o,n,j||0)},_mouseout:function(j){var o=j.relatedTarget;if(o)for(;o=o.parentNode;)if(o==this.wrapper)return;this._end(j)},_transitionEnd:function(j){if(j.target==this.scroller){this._unbind("webkitTransitionEnd");this._startAni()}},_startAni:function(){var j=this,
o=j.x,n=j.y,r=Date.now(),p,t,v;if(!j.animating)if(j.steps.length){p=j.steps.shift();if(p.x==o&&p.y==n)p.time=0;j.animating=true;j.moved=true;if(j.options.useTransition){j._transitionTime(p.time);j._pos(p.x,p.y);j.animating=false;p.time?j._bind("webkitTransitionEnd"):j._resetPos(0)}else{v=function(){var x=Date.now();if(x>=r+p.time){j._pos(p.x,p.y);j.animating=false;j.options.onAnimationEnd&&j.options.onAnimationEnd.call(j);j._startAni()}else{x=(x-r)/p.time-1;t=a.sqrt(1-x*x);x=(p.x-o)*t+o;j._pos(x,
(p.y-n)*t+n);if(j.animating)j.aniTime=h(v)}};v()}}else j._resetPos(400)},_transitionTime:function(j){this.scroller.style[c+"TransitionDuration"]=j+"ms"},_momentum:function(j,o,n,r,p){o=a.abs(j)/o;var t=o*o/0.0012,v=0;v=0;if(j>0&&t>n){v=p/(6/(t/o*6.0E-4));n+=v;o=o*n/t;t=n}else if(j<0&&t>r){v=p/(6/(t/o*6.0E-4));r+=v;o=o*r/t;t=r}t*=j<0?-1:1;v=o/6.0E-4;return{dist:t,time:v>>0}},_offset:function(j){for(var o=-j.offsetLeft,n=-j.offsetTop;j=j.offsetParent;){o-=j.offsetLeft;n-=j.offsetTop}return{left:o,top:n}},
_bind:function(j,o,n){(o||this.scroller).addEventListener(j,this,!!n)},_unbind:function(j,o,n){(o||this.scroller).removeEventListener(j,this,!!n)},destroy:function(){this.scroller.style[c+"Transform"]="";this._unbind(m,window);this._unbind(q);this._unbind(s);this._unbind(u);this._unbind(w);this._unbind("mouseout",this.wrapper);this.options.useTransition&&this._unbind("webkitTransitionEnd");this.options.onDestroy&&this.options.onDestroy.call(this)},refresh:function(){var j;this.wrapperW=this.wrapper.clientWidth;
this.wrapperH=this.wrapper.clientHeight;this.scrollerW=this.scroller.offsetWidth;this.scrollerH=this.scroller.offsetHeight;this.maxScrollX=this.wrapperW-this.scrollerW;this.maxScrollY=this.wrapperH-this.scrollerH;this.dirY=this.dirX=0;this.hScroll=this.options.hScroll&&this.maxScrollX<0;this.vScroll=this.options.vScroll&&(!this.options.bounceLock&&!this.hScroll||this.scrollerH>this.wrapperH);j=this._offset(this.wrapper);this.wrapperOffsetLeft=-j.left;this.wrapperOffsetTop=-j.top;this.scroller.style[c+
"TransitionDuration"]="0";this._resetPos(200)},scrollTo:function(j,o,n,r){var p=j;this.stop();p.length||(p=[{x:j,y:o,time:n,relative:r}]);j=0;for(o=p.length;j<o;j++){if(p[j].relative){p[j].x=this.x-p[j].x;p[j].y=this.y-p[j].y}this.steps.push({x:p[j].x,y:p[j].y,time:p[j].time||0})}this._startAni()},scrollToElement:function(j,o){var n;if(j=j.nodeType?j:this.scroller.querySelector(j)){n=this._offset(j);n.left+=this.wrapperOffsetLeft;n.top+=this.wrapperOffsetTop;n.left=n.left>0?0:n.left<this.maxScrollX?
this.maxScrollX:n.left;n.top=n.top>0?0:n.top<this.maxScrollY?this.maxScrollY:n.top;o=o===undefined?a.max(a.abs(n.left)*2,a.abs(n.top)*2):o;this.scrollTo(n.left,n.top,o)}},disable:function(){this.stop();this._resetPos(0);this.enabled=false;this._unbind(s);this._unbind(u);this._unbind(w)},enable:function(){this.enabled=true},stop:function(){k(this.aniTime);this.steps=[];this.animating=this.moved=false}};if(typeof exports!=="undefined")exports.iScroll=f;else window.iScroll=f})();/*
   http://www.github.com/tapquo/lungo/blob/master/LICENSE.txt
 @version   1.1
 @link      https://github.com/TapQuo/Lungo.js

 @author   Javier Jimenez Villar <javi@tapquo.com> || @soyjavi
 @author   Guillermo Pascual <pasku@tapquo.com> || @pasku1
*/
var LUNGO=LUNGO||{};LUNGO.VERSION="1.1";LUNGO.Attributes||(LUNGO.Attributes={});LUNGO.Data||(LUNGO.Data={});LUNGO.Sugar||(LUNGO.Sugar={});LUNGO.View||(LUNGO.View={});LUNGO.Device||(LUNGO.Device={});LUNGO.App=function(a){var c={id:1,name:"lungo_app",version:1,icon:""};return{init:function(f){c=a.Core.mix(c,f);a.Boot()},get:function(f){return c[f]}}}(LUNGO);LUNGO.Core=function(a,c){var f=Array.prototype,d=function(e,l){return c.isOwnProperty(e,l)},b=function(e){return c.toType(e)},g=function(e){return f.slice.call(e,0)};return{log:function(e,l){a.Core.isMobile()||console[e===1?"log":e===2?"warn":"error"](l)},execute:function(){var e=g(arguments),l=e.shift();b(l)==="function"&&l.apply(null,e)},bind:function(e,l){return function(){return l.apply(e,g(arguments))}},mix:function(){for(var e=e||{},l=0,i=arguments.length;l<i;l++){var h=arguments[l],k;for(k in h)if(d(h,
k))e[k]=h[k]}return e},isOwnProperty:d,toType:b,toArray:g,isMobile:function(){return c.isMobile()},environment:function(){return c.environment()}}}(LUNGO,Quo);LUNGO.dom=function(a){return $$(a)};LUNGO.Service=function(a,c){return{get:function(f,d,b,g){return c.get(f,d,b,g)},post:function(f,d,b,g){return c.post(f,d,b,g)},json:function(f,d,b){return c.json(f,d,b)},Settings:c.ajaxSettings}}(LUNGO,Quo);LUNGO.Router=function(a){var c={SHOW:"show",HIDE:"hide"},f=function(d){var b=false;if(a.dom(d).length>0)b=true;else a.Core.log(3,"Lungo.Router ERROR: The target "+d+" does not exists.");return b};return{section:function(d){d=d.indexOf("#")?"#"+d:d;if(f("section"+d)){a.dom(a.Router.History.current()).removeClass(c.SHOW).addClass(c.HIDE);a.dom(d).addClass(c.SHOW);a.Router.History.add(d)}},article:function(d,b){f(d+" article"+b)&&a.View.Article.show(d,b)},back:function(){a.dom(a.Router.History.current()).removeClass(c.SHOW);
a.Router.History.removeLast();a.dom(a.Router.History.current()).removeClass(c.HIDE).addClass(c.SHOW)}}}(LUNGO);LUNGO.Router.History=function(){var a=[],c=function(){return a[a.length-1]};return{add:function(f){f!==c()&&a.push(f)},current:c,removeLast:function(){a.length-=1}}}();LUNGO.View.Article=function(a){var c={ARTICLE:"article",NAVIGATION_ITEM:"a"},f={ACTIVE:"current"};return{show:function(d,b){var g=d+" "+c.NAVIGATION_ITEM;a.dom(g).removeClass(f.ACTIVE);g=a.dom(g+'[href="'+b+'"]');g.addClass(f.ACTIVE);(g=g.data("title"))&&a.dom(d+" header .title, "+d+" footer .title").text(g);a.dom(d+" "+c.ARTICLE).removeClass(f.ACTIVE);a.dom(b).addClass(f.ACTIVE)}}}(LUNGO);LUNGO.View.Resize=function(a){return{scroll:function(c){var f=c.children().first(),d=f.children().first();if(a.View.Scroll.isHorizontal(c)){d=f.children().length*d.width();f.style("width",d+"px")}else{var b=f.children().length;c=Math.floor(c.width()/d.width());d=Math.ceil(b/c)*d.height();f.style("height",d+"px")}},article:function(c,f,d,b){f=c.children(f);if(f.length>0){b=f[b]();c.children("article").style(d,b+"px")}},toolbars:function(){for(var c=".toolbar nav",f=a.dom(c),d=0,b=f.length;d<b;d++){c=
a.dom(f[d]);var g=c.children();c=c.width()/g.length;g.style("width",c+"px")}}}}(LUNGO);LUNGO.View.Template=function(a){var c={};return{create:function(f,d){c[f]=d},exists:function(f){return c[f]?true:false},get:function(f){return c[f]},binding:function(f,d,b,g){a.View.Template.Binding.create(f,d,b,g)}}}(LUNGO);LUNGO.View.Template.Binding=function(a,c){var f=/\{{.*?\}}/gi,d=function(g,e,l,i,h){if(a.View.Template.exists(l)){l=a.View.Template.get(l);var k=a.Core.toType(i);if(k==="array"){k="";for(var m=0,q=i.length;m<q;m++)k+=b(i[m],l);i=k}else if(k==="object")i=b(i,l);else{a.Core.log(3,"View.Template ERROR >> No type defined.");i=void 0}i=i;e=a.dom("#"+e);g.call(e,i);a.Core.execute(h)}else a.Core.log(3,"lng.View.Template.binding: id "+l+" not exists")},b=function(g,e){var l,i;for(i in g)if(a.Core.isOwnProperty(g,
i)){l=RegExp("{{"+i+"}}","g");e=e.replace(l,g[i])}return e.replace(f,"")};return{create:function(g,e,l,i){d(c.fn.html,g,e,l,i)},append:function(g,e,l,i){d(c.fn.append,g,e,l,i)},dataAttribute:function(g,e){var l=g.data(e.tag);if(l){l=e.html.replace("{{value}}",l);g.prepend(l)}}}}(LUNGO,Quo);LUNGO.View.Template.List=function(a){var c=null,f=function(){var d=c.order_field,b=c.order_type==="desc"?-1:1;d&&b&&c.data.sort(function(g,e){return g[d]<e[d]?-b:g[d]>e[d]?b:0})};return{create:function(d){c=d;c.container_id+="_list";d=false;var b=!!a.dom(c.container_id),g=a.View.Template.exists(c.template_id);if(b&&g){a.dom("#"+c.container_id).html("");b=a.Core.toType(c.data);if(b==="array"||b==="object")d=true}if(d){f();a.View.Template.Binding.create(c.container_id,c.template_id,c.data);d=a.dom("#"+
c.container_id).parent().attr("id");a.View.Scroll.create(d,{snap:"li"})}}}}(LUNGO);LUNGO.View.Scroll=function(a){var c={hScroll:false,vScroll:false,useTransition:true,momentum:true,lockDirection:true,fixedScrollbar:true,fadeScrollbar:true,hideScrollbar:true},f=function(b){return b.hasClass("horizontal")?true:false},d=function(b,g){a.Data.Cache.exists("scrolls")||a.Data.Cache.set("scrolls",{});var e=a.Data.Cache.get("scrolls");e[b]=new iScroll(b,g);a.Data.Cache.set("scrolls",e)};return{create:function(b,g){if(b){var e=a.dom("#"+b);setTimeout(function(){var l=false,i=e[0];if(i.clientHeight<
i.scrollHeight){l=true;var h=i.scrollHeight+90;a.dom(i).children().first().style("height",h+"px")}if(l){l=g;i=f(e)?"hScroll":"vScroll";l||(l={});l[i]=true;g=l=a.Core.mix(c,l);d(b,g)}},100)}else a.Core.log(3,"ERROR: Impossible to create a <scroll> without ID")},update:function(b,g){var e=a.dom("#"+b),l=e.children().first();if(l.length===0){e.html('<div id="'+b+'_scrl"></div>');l=e.children().first()}l.html(g);a.View.Resize.scroll(e);!a.Data.Cache.get("scrolls",b)&&d(b);a.Data.Cache.get("scrolls",b).refresh()},
remove:function(b){if(a.Data.Cache.exists("scrolls")){a.Data.Cache.get("scrolls",b).destroy();a.Data.Cache.remove("scrolls",b)}},isHorizontal:f}}(LUNGO);LUNGO.View.Aside=function(a){return{toggle:function(c){a.dom(c+" article").toggleClass("aside")}}}(LUNGO);LUNGO.View.Element=function(a){var c={BUBBLE:".bubble.count"};return{count:function(f,d){var b=a.dom(f);if(b)if(d>0){var g=b.children(c.BUBBLE);if(g.length>0)g.html(d);else{g=LUNGO.Attributes.Data.Count.html.replace("{{value}}",d);b.append(g)}}else b.children(c.BUBBLE).remove()}}}(LUNGO);LUNGO.Attributes.Data={Search:{tag:"search",selector:".list",html:'<li class="search {{value}}"><input type="search" placeholder="Search..."><a href="#" class="button" data-icon="search"></a></li>'},Count:{tag:"count",selector:"*",html:'<span class="bubble count">{{value}}</span>'},Search:{tag:"search",selector:"*",html:'<input type="search" placeholder="{{value}}"/><a href="#" class="button" data-icon="search"></a>'},Icon:{tag:"icon",selector:"*",html:'<span class="icon {{value}}"></span>'},Image:{tag:"image",
selector:"*",html:'<img src="{{value}}" class="icon" />'},Title:{tag:"title",selector:"header, footer, article",html:'<span class="title">{{value}}</span>'},Back:{tag:"back",selector:"header, footer",html:'<a href="#back" data-target="section" class="onleft button"><span class="icon {{value}}"></span></a>'}};LUNGO.Data.Cache=function(a){var c={},f=function(b){return arguments.length===1?c[b]:c[arguments[0]][arguments[1]]},d=function(b){return c[b]?true:false};return{set:function(b,g){c[b]=d(b)?a.Core.mix(f(b),g):g},get:f,remove:function(b){if(arguments.length===1)delete c[b];else delete c[arguments[0]][arguments[1]]},exists:d}}(LUNGO);LUNGO.Data.Sql=function(a){var c={name:"lungo_db",version:"1.0",size:65536,schema:[]},f=null,d=function(i,h){a.Core.log(1,"lng.Data.Sql >> "+i);f.transaction(function(k){k.executeSql(i,[],function(m,q){g(h,q)},l)})},b=function(i,h){var k="",m;for(m in i)if(a.Core.isOwnProperty(i,m)){var q=i[m];if(k)k+=" "+h+" ";k+=m+"=";k+=isNaN(q)?'"'+q+'"':q}return k},g=function(i,h){a.Core.toType(i)==="function"&&setTimeout(i,100,h)},e=function(i,h){var k="",m="",q;for(q in h)if(a.Core.isOwnProperty(h,q)){var s=
h[q];k+=k?", "+q:q;if(m)m+=", ";m+=isNaN(s)?'"'+s+'"':s}d("INSERT INTO "+i+" ("+k+") VALUES ("+m+")")},l=function(i,h){a.Core.log(3,"lng.Data.Sql >> "+h.code+": "+h.message)};return{init:function(i){c=a.Core.mix(c,i);if(f=openDatabase(c.name,c.version,c.name,c.size)){i=c.schema;var h=i.length;if(h)for(var k=0;k<h;k++){var m=i[k];m.drop===true&&d("DROP TABLE IF EXISTS "+m.name);var q=m.name;m=m.fields;var s="",u=void 0;for(u in m)if(a.Core.isOwnProperty(m,u)){if(s)s+=", ";s+=u+" "+m[u]}d("CREATE TABLE IF NOT EXISTS "+
q+" ("+s+");")}}else a.Core.log(3,"lng.Data.Sql >> Failed to connect to database.")},select:function(i,h,k){h=h?" WHERE "+b(h,"AND"):"";d("SELECT * FROM "+i+h,function(m){for(var q=[],s=0,u=m.rows.length;s<u;s++)q.push(m.rows.item(s));g(k,q)})},insert:function(i,h){if(a.Core.toType(h)==="object")e(i,h);else for(row in h)e(i,h[row])},update:function(i,h,k){i="UPDATE "+i+" SET "+b(h,",");if(k)i+=" WHERE "+b(k,"AND");d(i)},drop:function(i,h){var k=h?" WHERE "+b(h,"AND"):"";d("DELETE FROM "+i+k+";")},
execute:d}}(LUNGO);LUNGO.Data.Storage=function(){return{}}(LUNGO);LUNGO.Boot=function(a){return function(){a.Boot.Layout.start();a.Boot.Events.start();a.Boot.Data.start();a.Boot.Section.start();a.Boot.Article.start();a.Boot.Stats.start()}}(LUNGO);LUNGO.Boot.Stats=function(a){var c=function(){a.Service.post("http://www.lungojs.com/stats/",{name:a.App.get("name"),version:a.App.get("version"),icon:a.App.get("icon")},function(){})};return{start:function(){a.Core.isMobile()&&c()}}}(LUNGO);LUNGO.Boot.Layout=function(a){var c=null,f=null,d=function(){if(!location.hash||!c.addEventListener){c.scrollTo(0,1);var b=1,g=setInterval(function(){if(f.body){clearInterval(g);b="scrollTop"in f.body?f.body.scrollTop:1;c.scrollTo(0,b===1?0:1)}},15);c.addEventListener("load",function(){setTimeout(function(){c.scrollTo(0,b===1?0:1)},0)},false)}};return{start:function(){if(a.Core.isMobile()){c=window;f=c.document;if(c.innerHeight==356){a.dom("body").style("height","416px");d()}}}}}(LUNGO);LUNGO.Boot.Article=function(a){var c={LIST_IN_ARTICLE:"article.list",SCROLL_IN_ARTICLE:".scrollable",CHECKBOX_IN_ARTICLE:".checkbox, .radio"},f=function(e,l){for(var i=a.dom(e),h=0,k=i.length;h<k;h++){var m=a.dom(i[h]);a.Core.execute(l,m)}},d=function(e){if(e.children().length===0){var l=e.attr("id");e.append('<ul id="'+l+'_list"></ul>')}},b=function(e){e=e.attr("id");a.View.Scroll.create(e)},g=function(e){e.append("<span>&nbsp;</span>")};return{start:function(){f(c.LIST_IN_ARTICLE,d);f(c.SCROLL_IN_ARTICLE,
b);f(c.CHECKBOX_IN_ARTICLE,g)}}}(LUNGO);LUNGO.Boot.Data=function(a){return{start:function(){var c=a.Attributes.Data,f;for(f in c)if(a.Core.isOwnProperty(c,f))for(var d=c[f],b=a.dom(d.selector),g=0,e=b.length;g<e;g++){var l=a.dom(b[g]);a.View.Template.Binding.dataAttribute(l,d)}}}}(LUNGO);LUNGO.Boot.Events=function(a){var c=function(e){e.preventDefault()},f=function(){a.View.Resize.toolbars()},d=function(e){var l=a.dom(this);l=g(l);a.View.Aside.toggle(l);e.preventDefault()},b=function(e){var l=a.dom(this);switch(l.data("target")){case "section":var i=l.attr("href");i==="#back"?a.Router.back():a.Router.section(i);break;case "article":i=g(l);l=l.attr("href");a.Router.article(i,l);break;case "aside":i=g(l);a.View.Aside.toggle(i)}e.preventDefault()},g=function(e){return"#"+e.parent("section").attr("id")};
return{start:function(){a.dom(document).on("touchmove",c);a.dom(window).on("orientationchange",f);a.dom("aside a[href][data-target]").tap(d);a.dom("a[href][data-target]").tap(b)}}}(LUNGO);LUNGO.Boot.Section=function(a){var c={ARTICLE:"article",SECTION:"section"};return{start:function(){var f=a.dom(c.SECTION),d=f.first(),b="#"+d.attr("id");d.addClass("current");a.Router.History.add(b);if(a.Core.isMobile()){d=a.Core.environment();d.os.name==="ios"&&d.os.version>="5."&&f.style("position","fixed")}d=0;for(b=f.length;d<b;d++)a.dom(f[d]).children(c.ARTICLE).first().addClass("current");a.dom("aside").addClass("show");a.View.Resize.toolbars()}}}(LUNGO);
